language: EN
strict: true
strictness_threshold: high

output:
  file_path: results
  format: ALL  

sast:
  include:
    - .
  exclude:
    - node_modules
    - vendor

sca:
  include:
    - .
  exclude:
    - node_modules
    - vendor

ss:
  include:
    - .
  exclude:
    - tests
    - node_modules
    - vendor
